repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
      - id: mixed-line-ending
        exclude_types: ["xml"]
  - repo: local
    hooks:
      - id: seed-isort-config
        name: seed-isort-config
        entry: bin/seed-isort-config.sh
        language: script
        types: [python]
        pass_filenames: false
        stages: [manual]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: 1.19.1
    hooks:
      - id: prettier
minimum_pre_commit_version: "1.21"
